#!/bin/env bash
# (C) 2014-2022 - supaplextor cloned/exported code to https://github.com/supaplextor/rsyncplan
# (C) 2014 Scott Edwards - https://code.google.com/p/rsyncplan/

if [ x$1 = x ]
then
	echo "$0: rsync to remote and collect existing timestamp leaf"
	echo "  directories to hardlink with, saving space and xfer time/bw."
	echo ""
	echo "(C) 2022 GPLv2 https://github.com/supaplextor/rsyncplan"
	exit 1
fi


ops="--rsync-path=/usr/local/sbin/rsyncplan-exechook.sh \
	--timeout=1200 \
	--exclude=/swapfile \
	-iSaXAlx"

me=`hostname`
doRemoteLinks=true

TIMESTAMP_YMDHMS_NS=$(date "+%Y-%m-%d_%H%M%S.%N")
ifs=/
OFS=/backups/${me}/rootfs
RSYNCPLAN_DESINATION_HOST=$1

# rsyncplan -p /home -l home -h rsyncplan-dump

if ${doRemoteLinks} 
then
links=$(ssh "${RSYNCPLAN_DESINATION_HOST}" ls -1d "${OFS}/????-??-??*/" 2>/dev/null |\
	sort -nr |\
	head -n 20 |\
	awk '{print "--link-dest=__OFS__/"$1"/"}' |\
	sed -e "s#__OFS__##g" | tr -s /
	)
fi

rsync $ops $links $ifs "${RSYNCPLAN_DESINATION_HOST}":"${OFS}/${TIMESTAMP_YMDHMS_NS}/"
