#!/bin/env bash
# (C) 2014-2022 - supaplextor cloned/exported code to https://github.com/supaplextor/rsyncplan
# (C) 2014 Scott Edwards - https://code.google.com/p/rsyncplan/

RSYNCPLAN_DESINATION_HOST=$1
if [ x$1 = x ]
then
	echo "$0: rsync to remote and collect existing timestamp leaf"
	echo "  directories to hardlink with, saving space and xfer time/bw."
	echo ""
	echo "(C) 2022 GPLv2 https://github.com/supaplextor/rsyncplan"
	exit 1
fi


ops="--rsync-path=/usr/local/sbin/rsyncplan-exechook.sh \
	--timeout=120 \
	--exclude=/swapfile \
	--delete-after -4iSvPaXAplx"

me=`hostname`


ifs=/
OFS=/backups/${me}/rootfs

# rootfs is an alias for /
if [ Xrootfs = X$ifs ]
then
	ifs=/
fi

# Note: rsyncplan-exechook.sh will generate a timestamp
# directory for syncing into

echo rsync $ops $ifs "${RSYNCPLAN_DESINATION_HOST}":"${OFS}/"
